In [36]:
import pandas as pd
train=pd.read_csv('train.csv').dropna()
test=pd.read_csv('test.csv').dropna()

In [2]:
from nltk.corpus import stopwords

153

In [3]:
import re

In [8]:
def naiveScore(pds):    
    a=set(re.sub("[^\w]"," ",pds.question1).lower().split())
    b=set(re.sub("[^\w]"," ",pds.question2).lower().split())
    score=len(a^b)#/len(a|b)
    return score

In [ ]:
def naiveScore2(pds):    
    a=set(re.sub("[^\w]"," ",pds.question1).lower().split())
    b=set(re.sub("[^\w]"," ",pds.question2).lower().split())
    score=len(a^b)/len(a|b)
    return score

In [65]:
def wordbagbuilder(pds):
    a=set(pds.question1.replace('?','').split().lower())
    b=set(pds.question2.replace('?','').split().lower())
    ans=a^b
    return ans

In [69]:
pair_id=[]
score=[]
result=[]
for i in range(len(train)):
    score.append(naiveScore(train.iloc[i]))
    result.append(train.iloc[i].is_duplicate)
    pair_id.append(train.iloc[i].id)
    if i%5000==0:
        print (i)

0
5000
10000
15000
20000
25000
30000
35000
40000
45000
50000
55000
60000
65000
70000
75000
80000
85000
90000
95000
100000
105000
110000
115000
120000
125000
130000
135000
140000
145000
150000
155000
160000
165000
170000
175000
180000
185000
190000
195000
200000
205000
210000
215000
220000
225000
230000
235000
240000
245000
250000
255000
260000
265000
270000
275000
280000
285000
290000
295000
300000
305000
310000
315000
320000
325000
330000
335000
340000
345000
350000
355000
360000
365000
370000
375000
380000
385000
390000
395000
400000


In [44]:
new_pair_id=[]
new_score=[]

for i in range(len(test)):
    new_score.append(naiveScore(test.iloc[i]))
    new_pair_id.append(test.iloc[i].test_id)
    if i%5000==0:
        print (i)

0
5000
10000
15000
20000
25000
30000
35000
40000
45000
50000
55000
60000
65000
70000
75000
80000
85000
90000
95000
100000
105000
110000
115000
120000
125000
130000
135000
140000
145000
150000
155000
160000
165000
170000
175000
180000
185000
190000
195000
200000
205000
210000
215000
220000
225000
230000
235000
240000
245000
250000
255000
260000
265000
270000
275000
280000
285000
290000
295000
300000
305000
310000
315000
320000
325000
330000
335000
340000
345000
350000
355000
360000
365000
370000
375000
380000
385000
390000
395000
400000
405000
410000
415000
420000
425000
430000
435000
440000
445000
450000
455000
460000
465000
470000
475000
480000
485000
490000
495000
500000
505000
510000
515000
520000
525000
530000
535000
540000
545000
550000
555000
560000
565000
570000
575000
580000
585000
590000
595000
600000
605000
610000
615000
620000
625000
630000
635000
640000
645000
650000
655000
660000
665000
670000
675000
680000
685000
690000
695000
700000
705000
710000
715000
720000
725000
730

In [71]:
import numpy as np
import random as rd
train_index=rd.sample(list(range(len(train))),int(len(train)*.90))
valid=set(range(len(train)))-set(train_index)

In [62]:
tmp=pd.DataFrame({'pair_id':pair_id,'score':score,'result':result})                                

In [63]:
tmp.to_csv('naive.csv')

In [10]:
from sklearn.linear_model import LogisticRegression as LogisticRegression

In [72]:
lr=LogisticRegression()

In [73]:
train_train=np.array(score)[train_index]

In [75]:
lr.fit(np.array([train_train]).transpose(),np.array(result)[train_index])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [84]:
valid_set=np.array([np.array(score)[list(valid)]]).transpose()

In [85]:
predicted=lr.predict(valid_set)

In [64]:
tmp=pd.DataFrame({'is_duplicate':is_duplicate})   
tmp.to_csv('base.csv',index_label='test_id')

In [46]:
valid_set=np.array([np.array(new_score)]).transpose()

In [87]:
abs(predicted-np.array(result)[list(valid)]).sum()/len(predicted)

0.36127532216972963

In [82]:
from sklearn.metrics import confusion_matrix as confusion_matrix

In [88]:
confusion_matrix(np.array(result)[list(valid)],predicted)

array([[19955,  5612],
       [ 8994,  5868]], dtype=int64)

In [20]:
np.array(result)[list(valid)]

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [25]:
pre

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import log_loss
log_loss(np.array(result)[list(valid)],pre)

12.494242045935982

In [77]:
a=dict({'a':1})

In [79]:
import pandas as pd
import numpy as np
import re
import nltk
import string



KeyError: 'b'